# Numpy

In [97]:
import numpy as np

In [110]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [118]:
arr[len(arr) - 2]

3

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
arr.ndim

1

In [5]:
arr.shape

(4,)

In [43]:
z = np.array([[[2,3,1,4],[9,6,5,6]]])

In [44]:
print(z)

[[[2 3 1 4]
  [9 6 5 6]]]


In [67]:
np.reshape(z,(4,2))

array([[2, 3],
       [1, 4],
       [9, 6],
       [5, 6]])

In [46]:
z.reshape(2,4)

array([[2, 3, 1, 4],
       [9, 6, 5, 6]])

In [6]:
len(arr)

4

In [7]:
ar = np.array([
    [10,20,30,40],
    [30,60,90,120]
])

In [8]:
ar

array([[ 10,  20,  30,  40],
       [ 30,  60,  90, 120]])

In [9]:
ar.ndim

2

In [10]:
ar.shape

(2, 4)

In [11]:
len(ar)

2

In [12]:
ar.size

8

In [13]:
type(ar)

numpy.ndarray

In [43]:
ar.dtype

dtype('int32')

In [14]:
k = np.array(56)

In [15]:
print(k)

56


In [16]:
l = np.array([[[2,3,1,4],[9,6,5,6]],[[20,12,34,56],[13,25,46,32]]])

In [17]:
print (l)

[[[ 2  3  1  4]
  [ 9  6  5  6]]

 [[20 12 34 56]
  [13 25 46 32]]]


In [18]:
l.ndim

3

In [19]:
print(type (l))

<class 'numpy.ndarray'>


In [20]:
print(l.ndim)

3


In [21]:
arr = np.array([1,2,3,4])

In [23]:
print(arr)

[1 2 3 4]


In [35]:
r = np.asarray(arr,dtype="float",order = "c")

In [36]:
print(r)

[1. 2. 3. 4.]


In [31]:
v = np.array ([[1,2,3,4],[3,4,5,6]])

In [32]:
print(v)

[[1 2 3 4]
 [3 4 5 6]]


In [37]:
r = np.asarray(v, dtype="int", order = "f")

In [38]:
print(r)

[[1 2 3 4]
 [3 4 5 6]]


In [81]:
d = np.eye(3, dtype= "int")

In [82]:
print (d)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [85]:
w = np.full((5,4),333)

In [86]:
print(w)

[[333 333 333 333]
 [333 333 333 333]
 [333 333 333 333]
 [333 333 333 333]
 [333 333 333 333]]


In [92]:
q = np.ones((5,5), dtype = "int")

In [93]:
print(q)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [102]:
np.full((3,3), 'cat')

array([['cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat']], dtype='<U3')

In [108]:
np.random.randint(2,9,(4,5))

array([[7, 6, 2, 5, 5],
       [5, 3, 3, 8, 8],
       [3, 5, 8, 7, 5],
       [6, 6, 8, 2, 2]])

In [103]:
kv = np.arange(0, 100, 2, dtype="int")

In [104]:
print(kv)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [105]:
ka = np.linspace(0,50,10)

In [106]:
print(ka)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [107]:
ka.dtype

dtype('float64')

# slicing of array

[start index : stop index : step size]

[ : : ] = will take all the elements

Note: start index will include and stop index will exclude

In [2]:
arr = np.array([1,2,3,4])
arr[::]

array([1, 2, 3, 4])

In [3]:
arr[::2]

array([1, 3])

In [7]:
arr[1:3:] #the 3 rd index will excluded when we call it as a stop index

array([2, 3])

In [6]:
arr[2::]

array([3, 4])

2d array

In [9]:
ar = np.array([[10,20,30,40],[30,60,90,120]])
print(ar)

[[ 10  20  30  40]
 [ 30  60  90 120]]


In [11]:
ar[0,0:3]

array([10, 20, 30])

In [12]:
ar[1,:]

array([ 30,  60,  90, 120])

In [14]:
ar[1,1:4]

array([ 60,  90, 120])

In [15]:
ar[0:2 , 0:2]

array([[10, 20],
       [30, 60]])

3d array

In [16]:
h = np.array([[[2,3,1,4],[9,6,5,6]],[[20,12,34,56],[13,25,46,32]]])

In [18]:
h[0,0,0:4]

array([2, 3, 1, 4])

In [22]:
h[0:2,0:2,0:2]

array([[[ 2,  3],
        [ 9,  6]],

       [[20, 12],
        [13, 25]]])

# Axis

axis = 0 means, coloum wise & axis = 1 means, row wise.

In [24]:
bar =np.array([
    [2,3,5,7],
    [3,6,8,0],
    [1,12,3,44],
    [22,32,21,76]
])

print(bar)

[[ 2  3  5  7]
 [ 3  6  8  0]
 [ 1 12  3 44]
 [22 32 21 76]]


In [25]:
bar.shape 

(4, 4)

In [26]:
np.sort(bar,0) # axis = 0

array([[ 1,  3,  3,  0],
       [ 2,  6,  5,  7],
       [ 3, 12,  8, 44],
       [22, 32, 21, 76]])

In [28]:
np.sort(bar,1) # axis = 1

array([[ 2,  3,  5,  7],
       [ 0,  3,  6,  8],
       [ 1,  3, 12, 44],
       [21, 22, 32, 76]])

In [125]:
bar[3,3]

76

In [126]:
bar[2]

array([ 1, 12,  3, 44])

In [128]:
bar[1:3]

array([[ 3,  6,  8,  0],
       [ 1, 12,  3, 44]])

In [129]:
bar[-2,-1]

44

In [131]:
bar[1:3 ,[-2,-1]]

array([[ 8,  0],
       [ 3, 44]])

In [132]:
bar[0,0] = 99
print(bar)

[[99  3  5  7]
 [ 3  6  8  0]
 [ 1 12  3 44]
 [22 32 21 76]]


In [133]:
bar[1] = bar[2]
print(bar)

[[99  3  5  7]
 [ 1 12  3 44]
 [ 1 12  3 44]
 [22 32 21 76]]


In [135]:
bar [[0,1,2,3],[0,1,2,3]] = [11,11,11,11]
print(bar)

[[11  3  5  7]
 [ 1 11  3 44]
 [ 1 12 11 44]
 [22 32 21 11]]


# 3 dimension array

In [137]:
zoo = np.array([
[   [12,34],
    [32,13],
    [67,77],
],
[   [43,42],
    [87,65],
    [46,98],    
]
])

print(zoo)

[[[12 34]
  [32 13]
  [67 77]]

 [[43 42]
  [87 65]
  [46 98]]]


In [139]:
zoo.ndim

3

In [140]:
zoo.shape

(2, 3, 2)

In [142]:
zoo[1,:,1] = 999
print(zoo)

[[[ 12  34]
  [ 32  13]
  [ 67  77]]

 [[ 43 999]
  [ 87 999]
  [ 46 999]]]


In [146]:
zoo[0,:,0] = 555
print(zoo)

[[[555  34]
  [555  13]
  [555  77]]

 [[ 43 999]
  [ 87 999]
  [ 46 999]]]


In [148]:
zoo[1,:,0] = 333
print(zoo)

[[[555  34]
  [555  13]
  [555  77]]

 [[333 999]
  [333 999]
  [333 999]]]


In [149]:
zoo[0,:,1] = 222
print(zoo)

[[[555 222]
  [555 222]
  [555 222]]

 [[333 999]
  [333 999]
  [333 999]]]


# Array operation

In [150]:
fo= np.array([[10,20,30],[40,50,60]])
bo= np.array([[70,80,90],[100,110,120]])

In [151]:
print(fo)

[[10 20 30]
 [40 50 60]]


In [152]:
print(bo)

[[ 70  80  90]
 [100 110 120]]


In [153]:
fo + bo

array([[ 80, 100, 120],
       [140, 160, 180]])

In [154]:
bo - fo

array([[60, 60, 60],
       [60, 60, 60]])

In [155]:
fo * bo

array([[ 700, 1600, 2700],
       [4000, 5500, 7200]])

In [156]:
fo / bo

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

Added 5 to every element of the matrix fo

In [158]:
fo + np.full((2,3),5)

array([[15, 25, 35],
       [45, 55, 65]])

In [159]:
fo + 5

array([[15, 25, 35],
       [45, 55, 65]])

# Broadcasting

allows arithmetic operations of arrays that are different size and shape

In [29]:
a = np.array([2,3,4,5])
print(a)

[2 3 4 5]


In [30]:
a + 2

array([4, 5, 6, 7])

In [34]:
m = np.array([[1,2],[3,4],[5,6]])
print(m)

[[1 2]
 [3 4]
 [5 6]]


In [37]:
m.shape

(3, 2)

In [35]:
n = np.array([5,7])

In [38]:
n.shape

(2,)

In [36]:
m+n

array([[ 6,  9],
       [ 8, 11],
       [10, 13]])

In [39]:
x = np.array([[10],[20],[30]])

In [40]:
y = np.array([1,2,3])

In [41]:
x+y

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

#[1 1 1]     #[10 20 30]
#[2 2 2]  #+ #[10 20 30]
#[3 3 3]     #[10 20 30]

# join & split two different arrays

In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(2,3)

In [3]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
b = np.arange(7,13).reshape(2,3)
print(b)

[[ 7  8  9]
 [10 11 12]]


In [6]:
np.concatenate((a,b), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
np.concatenate((a,b),axis = 1)

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [8]:
np.stack((a,b))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
np.stack((a,b), axis = 1)

array([[[ 0,  1,  2],
        [ 7,  8,  9]],

       [[ 3,  4,  5],
        [10, 11, 12]]])

In [10]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
np.hstack((a,b))

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [67]:
import numpy as np

In [54]:
a = np.array ([[1,2], [3,4]])
b = np.array([[9,9], [8,8]])


In [41]:
a

array([[1, 2],
       [3, 4]])

In [47]:
b

array([[9, 9],
       [8, 8]])

In [48]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [9, 9],
       [8, 8]])

In [56]:
p = np.arange (1,11)

In [57]:
p

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
np.split(p,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [61]:
np.hsplit(p,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [63]:
q = np.arange(1,13).reshape(6,2)
print(q)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [64]:
np.vsplit(q,2)

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [65]:
np.hsplit(q,2)

[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]])]

In [66]:
np.split(q,3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

# sort

In [68]:
a = np.array ([[50,40,30],[10,20,60]])
a


array([[50, 40, 30],
       [10, 20, 60]])

In [69]:
np.sort(a)

array([[30, 40, 50],
       [10, 20, 60]])

# inserting elements

In [70]:
a = np.arange(1,12)

In [71]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [72]:
np.insert(a,11,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
np.insert(a,9,100)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 100,  10,  11])

In [74]:
np.insert(a,(1,3,5,7),1000)

array([   1, 1000,    2,    3, 1000,    4,    5, 1000,    6,    7, 1000,
          8,    9,   10,   11])

In [78]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [79]:
np.insert(a,1,23,axis = 0)

array([[ 1,  2],
       [23, 23],
       [ 3,  4]])

In [80]:
np.insert(a,1,[23,24],axis = 0)

array([[ 1,  2],
       [23, 24],
       [ 3,  4]])

In [81]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [82]:
np.append(a,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [91]:
b= np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [92]:
np.append(b,[[4,5,6]],axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [4, 5, 6]])

In [96]:
np.delete(a,[[4,5,6]],axis = 0)

array([ 1,  2,  3,  4,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Matrix

In [98]:
a = np.array([[2,4],[6,8]])
b = np.array([[12,23],[14,25]])
print(a)
print(b)

[[2 4]
 [6 8]]
[[12 23]
 [14 25]]


In [99]:
a+b

array([[14, 27],
       [20, 33]])

In [100]:
a.dot(b)  #matrix multiplication or

array([[ 80, 146],
       [184, 338]])

In [101]:
np.dot(a,b)  #dot product of arrays

array([[ 80, 146],
       [184, 338]])

In [102]:
a.T

array([[2, 6],
       [4, 8]])

In [106]:
a = np.matrix ([[1,2],[6,9]])
a

matrix([[1, 2],
        [6, 9]])

In [108]:
b = np.matrix ([[2,4],[7,8]])
b

matrix([[2, 4],
        [7, 8]])

In [109]:
a+b

matrix([[ 3,  6],
        [13, 17]])

In [110]:
a - b 

matrix([[-1, -2],
        [-1,  1]])

In [111]:
a.dot(b)

matrix([[16, 20],
        [75, 96]])

In [112]:
a/b

matrix([[0.5       , 0.5       ],
        [0.85714286, 1.125     ]])

In [113]:
a.T

matrix([[1, 6],
        [2, 9]])

In [114]:
b.T

matrix([[2, 7],
        [4, 8]])

In [116]:
# linear algebra of matrices (inverse, power of a matrix, linear equations, determinants...)

In [118]:
np.linalg.inv(b) # inverse of a matrix

matrix([[-0.66666667,  0.33333333],
        [ 0.58333333, -0.16666667]])

In [119]:
np.linalg.matrix_power(b,n=0) #identity matrix

matrix([[1, 0],
        [0, 1]])

In [120]:
np.linalg.matrix_power(b,n=1) #matrix itself

matrix([[2, 4],
        [7, 8]])

In [121]:
np.linalg.matrix_power(b,n=2) #squared matrix

matrix([[32, 40],
        [70, 92]])

In [123]:
np.linalg.matrix_power(b,n= - 1) # inverse of the matrix

matrix([[-0.66666667,  0.33333333],
        [ 0.58333333, -0.16666667]])

In [124]:
np.linalg.matrix_power(b,n= -2)

matrix([[ 0.63888889, -0.27777778],
        [-0.48611111,  0.22222222]])

In [126]:
np.linalg.inv(b) #inverse

matrix([[-0.66666667,  0.33333333],
        [ 0.58333333, -0.16666667]])

# mathemetical & statistical operation

shape of two array must be equal, second array must have atleast one dimension and the number & elements in that dimension should be equal to first array. ex: a = (3,3) mill not go with b = (2,2),or (2,2,2) they will go with anything b = (3,) like this. it is called broadcasting.

In [127]:
a = ([[1,2],[3,4]])
b = ([5,6])
print(a)
print(b)

[[1, 2], [3, 4]]
[[5, 6]]


In [131]:
np.add(a,b)

array([[ 6,  8],
       [ 8, 10]])

In [132]:
np.subtract(a,b)

array([[-4, -4],
       [-2, -2]])

In [133]:
np.multiply(a,b)

array([[ 5, 12],
       [15, 24]])

In [134]:
np.mod(a,b) # is is the reminder of all divisor

array([[1, 2],
       [3, 4]])

In [135]:
np.power(a,b)

array([[   1,   64],
       [ 243, 4096]])

In [137]:
np.power(a,3)

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [138]:
np.reciprocal(a)

array([[1, 0],
       [0, 0]])

In [139]:
a = np.array ([[12,13,45],[23,21,34],[23,43,47]])
a

array([[12, 13, 45],
       [23, 21, 34],
       [23, 43, 47]])

In [141]:
np.amin(a) #min element of a array

12

In [142]:
np.amax(a) #max element of a array

47

In [144]:
np.amin(a,axis = 0) #gives the smallest value of each row

array([12, 13, 34])

In [146]:
np.amin(a,axis = 1)

array([12, 21, 23])

In [145]:
np.amax(a,axis = 1) #max value

array([45, 34, 47])

In [147]:
np.amax(a,axis = 0)

array([23, 43, 47])

In [148]:
np.average(a)

29.0

In [149]:
np.mean(a)

29.0

In [150]:
np.mean(a,axis =0)

array([19.33333333, 25.66666667, 42.        ])

In [151]:
np.mean(a,axis =1)

array([23.33333333, 26.        , 37.66666667])

In [152]:
a

array([[12, 13, 45],
       [23, 21, 34],
       [23, 43, 47]])

In [153]:
np.median(a)

23.0

In [155]:
np.median(a, axis = 0)

array([23., 21., 45.])

In [156]:
np.median(a, axis =1)

array([13., 23., 43.])

In [157]:
np.var(a)

164.66666666666666

In [158]:
np.std(a)

12.832251036613439